/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dark: typeof import('./components/common/ThemeToggler/components/Dark.vue')['default']
    DAside: typeof import('./components/docs/Layout/DAside.vue')['default']
    DContent: typeof import('./components/docs/Layout/DContent.vue')['default']
    DFooter: typeof import('./components/docs/Layout/DFooter.vue')['default']
    DHeader: typeof import('./components/docs/Layout/DHeader.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    GFooter: typeof import('./components/layout/GFooter.vue')['default']
    GHeader: typeof import('./components/layout/GHeader.vue')['default']
    Light: typeof import('./components/common/ThemeToggler/components/Light.vue')['default']
    MBackground: typeof import('./components/main/MBackground.vue')['default']
    MLoading: typeof import('./components/main/MLoading.vue')['default']
    NavFooter: typeof import('./components/nav/NavFooter.vue')['default']
    NavHeader: typeof import('./components/nav/NavHeader.vue')['default']
    NavLink: typeof import('./components/common/NavLink/index.vue')['default']
    NavThemeToggler: typeof import('./components/nav/components/NavThemeToggler.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggler: typeof import('./components/common/ThemeToggler/index.vue')['default']
  }
}
